
services:
  clinica_veterinaria:
    build: ej2clinicaveterinaria
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://ej2clinicaveterinaria:3306/ej2clinicaveterinaria?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1614
    restart: always
    depends_on:
      ej2clinicaveterinaria:
          condition: service_healthy
  ej2clinicaveterinaria:
    image: mysql:9.1.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1614
      MYSQL_PASSWORD: 1614
      MYSQL_DATABASE: ej2clinicaveterinaria
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10